[build]
target = "x86_64-Mindada.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-Mindada]
rustflags = ["-C", "link-arg=-T./linker.ld"]